a = 'I love python forever'
b = a.endswith('R')
c = a.find('x', 2)
d = a.index('e')
e = a.join(' 520 ')
f = a.ljust(100, '♥')
g = a.partition('python')
h = a.rjust(100, '♥')
i = a.replace('python', 'PY')
j = a.translate(str.maketrans('python', 'PYTHON'))
print('endswith :', b)
print('find :', c)
print('index :', d)
print('join :', e)
print('ljust :', f)
print('partition :', g)
print('rjust :', h)
print('replace :', i)
print('translate :', j)
print('a.translate :', a.translate)
